# action.yml
name: 'Confluence'
description: 'Publish markdown and PDFs to a confluence page'
inputs:
  user:
    description: 'confluence user to auth as'
    required: true
  password:
    description: 'confluence password/token to auth as'
    required: true
  page:
    description: 'confluence page id to post documents to'
    required: true
  title:
    description: 'Title for confluence page'
    required: true
  files:
    description: 'One or more files to add to document. Comma separated local paths.'
    required: true
  space:
    description: 'The confluence space.'
    required: true
    default: GS
  uri:
    description: 'The confluence URI.'
    required: true
    default: 'https://socialgamingnetwork.jira.com/wiki/rest/api/content'
  toc:
    description: 'If true, include table of contents'
    required: false
    default: 'false'
  toPdf:
    description: 'If true, convert everything to PDF before posting'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps: 
    - run: '$GITHUB_ACTION_PATH/confluence.sh --user "${{inputs.user}}" --password "${{inputs.password}}" --page "${{inputs.page}}" 
           --title "${{inputs.title}}" --files "${{inputs.files}}" --space "${{inputs.space}}" --url "${{inputs.uri}}" 
           --toc "${{inputs.toc}}" --toPdf "${{inputs.toPdf}}"'
      shell: bash