# action.yml
name: "Post Release Status To Slack"
description: "Post Release Success/Failure/Cancel job status to Slack using bot"
author: "Mindjolt"

inputs:
  job-status:
    description: "Job status i.e. Success/Failure/Cancelled"
    required: true
  slack-bot-token:
    description: "Slack bot token used to send message to slack channel"
    required: true
  channel:
    description: "Slack channel where job status message will be posted"
    required: true
  version:
    description: "Version of the release"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.job-status }}
    - ${{ inputs.slack-bot-token }}
    - ${{ inputs.channel }}
    - ${{ inputs.version }}

branding:
  icon: "activity"
  color: "green"