# action.yml
name: 'Nuget Publish'
description: 'Publishes to local nuget repository on artifactory. Requires nuget already installed.'
inputs:
  user:
    description: 'Artifactory user to auth as'
    required: false
  password:
    description: 'Artifactory password to auth as'
    required: false
  rootUrl:
    description: 'Artifactory url root'
    required: false
  packagePath:
    description: 'Path to the .nupkg package'
    required: true
  
runs:
  using: 'docker'
  image: docker://sgn0/nuget-publish-action:v2
  entrypoint: '/publish.sh'
  