name: 'Build tags'
description: 'Generate tags based on build version and repo data'
inputs:
  build-version:  # from package.json, build.gradle or build.sbt
    description: 'committed package version'
    required: false
  tag-separator:  # from package.json, build.gradle or build.sbt
    description: 'tag separator'
    required: false
    default: "\n"
  base-tags:  # from package.json, build.gradle or build.sbt
    description: 'list of tags (one tag per line)'
    required: false
    default: []
outputs:
  tags: # id of output
    description: 'new line separated (by default) list of tags'
runs:
  using: 'node12'
  main: 'index.js'
