name: 'NuGet Publish GitHub'
description: 'Publishes to GitHub NuGet registry. Requires dotnet, nuget and Docker.'

inputs:
  user:
    description: 'GitHub username or bot name (use ${GITHUB_ACTOR} in GitHub Actions)'
    required: false
  password:
    description: 'GitHub personal access token (use ${GITHUB_TOKEN} in GitHub Actions)'
    required: false  
  packagePath:
    description: 'Path to the .nupkg package'
    required: true

runs:
  using: 'docker'
  image: 'docker://ghcr.io/mindjolt/actions/nuget-publish-github-action:v2'  
  entrypoint: '/publish.sh'
  

