name: Build

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
        description: tag to be added to docker images and git repo
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
        description:  tag to be added to docker images and git repo

jobs:
  Build:
    runs-on: [ self-hosted, k8s-svc-runners-dind ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          registry: ghcr.io
          password: ${{ github.token }}

      - name: snapshot-bump docker meta
        id: snapshot-bump-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/actions/snapshot-bump-action
          tags: |
            type=raw,value=${{ inputs.tag }}
      - name: Build and push snapshot-bump
        uses: docker/build-push-action@v3
        with:
          context: ./snapshot-bump
          push: true
          tags: "${{ steps.snapshot-bump-meta.outputs.tags }}"
          labels: "${{ steps.snapshot-bump-meta.outputs.labels }}"

      - name: confluence docker meta
        id: confluence-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/actions/confluence-action
          tags: |
            type=raw,value=${{ inputs.tag }}
      - name: Build and push confluence
        uses: docker/build-push-action@v3
        with:
          context: ./confluence
          push: true
          tags: "${{ steps.confluence-meta.outputs.tags }}"
          labels: "${{ steps.confluence-meta.outputs.labels }}"

      - name: nuget docker meta
        id: nuget-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/actions/nuget-publish-action
          tags: |
            type=raw,value=${{ inputs.tag }}
            
      - name: nuget-publish-github docker meta
        id: nuget-publish-github-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/actions/nuget-publish-github-action
          tags: |
            type=raw,value=${{ inputs.tag }}
      - name: Build and push nuget-publish-github
        uses: docker/build-push-action@v3
        with:
          context: ./nuget-publish-github
          push: true
          tags: "${{ steps.nuget-publish-github-meta.outputs.tags }}"
          labels: "${{ steps.nuget-publish-github-meta.outputs.labels }}"

#      - name: Build and push nuget
#        uses: docker/build-push-action@v3
#        with:
#          context: ./nuget-publish
#          push: true
#          tags: "${{ steps.nuget-meta.outputs.tags }}"
#          labels: "${{ steps.nuget-meta.outputs.labels }}"

      - name: config docker meta
        id: config-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/actions/config-service-action
          tags: |
            type=raw,value=${{ inputs.tag }}
      - name: Build and push config
        uses: docker/build-push-action@v3
        with:
          context: ./config
          push: true
          tags: "${{ steps.config-meta.outputs.tags }}"
          labels: "${{ steps.config-meta.outputs.labels }}"

      - name: sbt-csharp-build docker meta
        id: sbt-csharp-build-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/actions/csharp-build-env
          tags: |
            type=raw,value=${{ inputs.tag }}
#      - name: Build and push sbt-unity
#        uses: docker/build-push-action@v3
#        with:
#          context: ./sbt-unity/csharp-build-image
#          push: true
#          tags: "${{ steps.sbt-csharp-build-meta.outputs.tags }}"
#          labels: "${{ steps.sbt-csharp-build-meta.outputs.labels }}"

      - name: sbt-image docker meta
        id: sbt-image-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/actions/sbt-unity-action
          tags: |
            type=raw,value=${{ inputs.tag }}
#      - name: Build and push sbt-image
#        uses: docker/build-push-action@v3
#        with:
#          context: ./sbt-unity/sbt-image
#          push: true
#          build-args: "tag=${{ inputs.tag }}"
#          tags: "${{ steps.sbt-image-meta.outputs.tags }}"
#          labels: "${{ steps.sbt-image-meta.outputs.labels }}"
