name: develop-build

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    needs: prep-releaseaction interpolation
    if: needs.prep-release.outputs.release_created
    secrets: inherit
    uses: './.github/workflows/build.yml'
    with:
      tag: develop

