name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
jobs:
  Build:
    runs-on: [ self-hosted, docker ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
    - name: Build Confluence Docker Image
      run: |
        cd confluence-docker
        docker build . --file Dockerfile --tag sgn0/confluence-action:${{steps.vars.outputs.tag}} 
        docker push sgn0/confluence-action:${{steps.vars.outputs.tag}}
