name: release-prep

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      version: ${{ steps.release-please.outputs.version }}
    steps:
      - id: 'release-please'
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          default-branch: main

  build:
    needs: prep-release
    if: needs.prep-release.outputs.release_created
    uses: './.github/workflows/build.yml'
    with:
      version: ${{ needs.prep-release.outputs.package_version }}

  update-develop-branch:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: everlytic/branch-merge@1.1.4
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: develop
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
